name: foundit
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_map: ^6.1.0
  image_picker: ^1.0.7
  firebase_storage: ^11.7.0
  flutter_share: ^2.0.0
  fluttertoast: ^8.2.4
  geolocator: ^11.0.0
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/bottom_bar/
    - assets/images/login_and_signup/
  fonts :
    - family: Poppins
      fonts :
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800